/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fifteen.puzzle.app;

import fifteen.puzzle.list.LinkedList;

import static fifteen.puzzle.utilities.StringUtils.join;
import static fifteen.puzzle.utilities.StringUtils.split;
import static fifteen.puzzle.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
