/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fifteenpuzzle;

import javafx.application.Application;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;

public class Main extends Application{
 // Ukuran window game
 private static final int WINDOW_WIDTH = 420;
 private static final int WINDOW_HEIGHT = 500;
 private static final int margin = 10;

 // Ukuran game field
 private static int WIDTH = 4;
 private static int HEIGHT = 4;

 private Parent createContent() {
     Pane root = new Pane();
     root.setPrefSize(WINDOW_WIDTH,WINDOW_HEIGHT);

     // Set ukuran tile supaya semua tile dapat masuk ke dalam window
     Tile.TILE_SIZE = (WINDOW_WIDTH-(2*margin)) / WIDTH;

     // Membuat game baru
     Field gameField = new Field(WIDTH, HEIGHT);

     // Menambahkan button reset
     Button resetButton = new Button("Reset");
     resetButton.setTranslateX(350);
     resetButton.setTranslateY(420);

     // Menambahkan action event untuk button
     EventHandler<ActionEvent> event = new EventHandler<ActionEvent>(){
         public void handle(ActionEvent e){
             gameField.newGame();
         }
     };

     // Assign event untuk button
     resetButton.setOnAction(event);
     
     // Menambahkan game field ke window
     root.getChildren().add(gameField);
     root.getChildren().add(resetButton);

     return root;
 }

 @Override
 public void start(Stage primaryStage) {
     primaryStage.setTitle("Fifteen");
     primaryStage.setScene( new Scene( createContent()));
     primaryStage.show();
 }

 public static void main(String[] args) {
     if(args.length == 1){
        WIDTH = Integer.parseInt(args[0]);
        HEIGHT = Integer.parseInt(args[0]);
     }
     launch(args);
 }

}
