/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fifteenpuzzle;

import java.io.IOException;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;
import javafx.scene.layout.StackPane;

public class fifteen_puzzle extends Application{
    private static int size;

    public static void main(String[] args) {
        if (args[0] != null) {
            size = Integer.parseInt(args[0]);
        }
        else{
            size = 4;
        }
        launch(args);
    }

    public void start(Stage stage) throws Exception {
        // Puzzle puzzle = new Puzzle(size);
        stage.setTitle("Fifteen Puzzle");
        stage.setResizable(false);
        Scene scene = new Scene(new StackPane(), 460, 700);
        stage.setScene(scene);
        stage.show();
    }
}
