/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fifteenpuzzle;

import javafx.application.Application;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;

public class fifteen_puzzle extends Application{
 // window size
 private static final int WINDOW_WIDTH = 400;
 private static final int WINDOW_HEIGHT = 400;

 // game field size
 private static int WIDTH = 4;
 private static int HEIGHT = 4;

 private Parent createContent() {
     Pane root = new Pane();
     root.setPrefSize(WINDOW_WIDTH,WINDOW_HEIGHT);

     // set tile size to fit all the tiles in the window
     Tile.TILE_SIZE = WINDOW_WIDTH / WIDTH;

     // create a new game field using WIDTH and HEIGHT constants
     Field gameField = new Field(WIDTH, HEIGHT);

     // add game field to the window
     root.getChildren().add(gameField);

     return root;
 }

 @Override
 public void start(Stage primaryStage) {
     primaryStage.setTitle("Fifteen");
     primaryStage.setScene( new Scene( createContent()));
     primaryStage.show();
 }

 // entry point of program
 public static void main(String[] args) {
     if(args.length == 1){
        WIDTH = Integer.parseInt(args[0]);
        HEIGHT = Integer.parseInt(args[0]);
     }
     launch(args);
 }

}
